-- clean up
DROP TYPE "T_PARAMS";
DROP TYPE "T_DATA";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
DROP TABLE "PARAMS";
DROP TABLE "RESULTS";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP" ('EMLUSER', 'SCORE_DIGITS');

-- import MNIST table

-- create table types
CREATE TYPE "T_PARAMS" AS TABLE ("Parameter" VARCHAR(100), "Value" VARCHAR(100));
CREATE TYPE "T_DATA" AS TABLE ("Label" INTEGER, "Image" BLOB);
CREATE TYPE "T_RESULTS" AS TABLE ("Label" INTEGER, "Class1" VARCHAR(100), "Class2" VARCHAR(100), "Class3" VARCHAR(100), "Class4" VARCHAR(100), "Class5" VARCHAR(100), "Class6" VARCHAR(100), "Class7" VARCHAR(100), "Class8" VARCHAR(100), "Class9" VARCHAR(100), "Class10" VARCHAR(100), "Score1" FLOAT, "Score2" FLOAT, "Score3" FLOAT, "Score4" FLOAT, "Score5" FLOAT, "Score6" FLOAT, "Score7" FLOAT, "Score8" FLOAT, "Score9" FLOAT, "Score10" FLOAT);

-- create signature table then generate stored procedure
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'EMLUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'EMLUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'EMLUSER', 'T_RESULTS', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE" ('EML', 'PREDICTM', 'EMLUSER', 'SCORE_DIGITS', "SIGNATURE");

-- create tables
CREATE TABLE "PARAMS" LIKE "T_PARAMS";
CREATE TABLE "RESULTS" LIKE "T_RESULTS";

-- run time

-- params
TRUNCATE TABLE "PARAMS";
INSERT INTO "PARAMS" VALUES ('Model', 'mnist'); -- mandatory: model name (optional: signature name)
--INSERT INTO "PARAMS" VALUES ('Deadline', '1000'); -- optional: max milliseconds to wait

-- scoring : results inline
CALL "SCORE_DIGITS" ("PARAMS", "MNIST", ?);

-- scoring : results in table
TRUNCATE TABLE "RESULTS";
CALL "SCORE_DIGITS" ("PARAMS", "MNIST", "RESULTS") WITH OVERVIEW;
SELECT * FROM "RESULTS";