-- CLEANUP
DROP REMOTE SOURCE "TensorFlowModelServer";
DROP TABLE "PARAMS";
DELETE FROM "_SYS_AFL"."EML_MODEL_CONFIGURATION" WHERE "Parameter"='RemoteSource' and "Value"='TensorFlowModelServer';

-- CREATE REMOTE SOURCE
CREATE REMOTE SOURCE "TensorFlowModelServer" ADAPTER "grpc" CONFIGURATION 'server=localhost;port=9000';

-- REGISTER MODEL
INSERT INTO "_SYS_AFL"."EML_MODEL_CONFIGURATION" VALUES ('mnist', 'RemoteSource', 'TensorFlowModelServer');
SELECT * FROM "_SYS_AFL"."EML_MODEL_CONFIGURATION";

-- CREATE PARAMS TABLE (USED IN SUBSEQUENT CALLS)
CREATE TABLE "PARAMS" ("Parameter" VARCHAR(100), "Value" VARCHAR(100));

-- APPLY REGISTERED MODELS
CALL "_SYS_AFL"."EML_CTL_PROC" ('UpdateModelConfiguration', "PARAMS", ?);

-- VERIFY MODEL IS UP AND RUNNING ON REMOTE SOURCE
INSERT INTO "PARAMS" VALUES ('Model', 'mnist');
CALL "_SYS_AFL"."EML_CHECKDESTINATION_PROC" ("PARAMS", ?);
